# -*- coding: utf-8 -*-
"""crime-against-women-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_DWLCI9lJxwvW2o4M4F1QwW8nmFD560

# Crime Against Women in India- A data Analysis Project


*The country where we worship goddess is also the worst country for women.*
Crime against women reported every two minute over the last decade.

**About Dataset:** Dataset is from kaggle: [View it here](https://www.kaggle.com/greeshmagirish/crime-against-women-20012014-india).
This dataset contains statistics of various crimes cases against women from the year 2001-2014 with State or Union Territories.

Downloading all the required packages we will require to run this notebook using PIP.
"""

!pip install jovian opendatasets pandas plotly --upgrade --quiet

#importing all the necessaary libaries

import os
import opendatasets as od
import jovian
import pandas as pd
import json
import plotly.express as px
import plotly.graph_objects as go
import IPython

"""Let's begin by downloading the data, and listing the files within the dataset.
We will be downloading the dataset from Kaggle.
Link to download dataset is mentioned above.
"""

dataset_url ="https://www.kaggle.com/greeshmagirish/crime-against-women-20012014-india"
od.download(dataset_url)

data_dir = './crime-against-women-20012014-india'

os.listdir(data_dir)

project_name = "crime-against-women-final" # change this (use lowercase letters and hyphens only)

jovian.commit(project=project_name)

crimes_df = pd.read_csv(data_dir+'/crimes_against_women_2001-2014.csv')
crimes_df.drop(['Unnamed: 0'],axis=1,inplace=True)

crimes_df.shape

"""This dataset has 10677 rows and 10 columns."""

print(crimes_df['STATE/UT'].unique())
len(crimes_df['STATE/UT'].unique())

"""There are many repeated rows. In some places, different letter cases are used for the same word as in Assam and ASSAM. Other places have improper spacing and shorthands are used for the state/ut name.
Delhi is repeated with the suffix UT.

There are were also some rows which contain total for that particular district which we don't want. So we are dropping all the columns which contain the word TOTAL.
"""

#Changing the cases of all the column to uppercase
def uppername(dataset):
    for columns in dataset.columns[:2]:
        dataset[columns] = dataset[columns].str.upper()
    return dataset
uppername(crimes_df)

#Droping unwanted columns
crimes_df.drop(crimes_df[(crimes_df['DISTRICT']=="TOTAL")|(crimes_df['DISTRICT']=="TOTAL DISTRICT(S)")|(crimes_df['DISTRICT']=="DELHI UT TOTAL")|(crimes_df['DISTRICT']=="ZZ TOTAL") ].index, inplace = True)

"""**Note: Merging TELANGANA and ANDHRA PRADESH because Telangana was formed in 2014 before that it was a part of Andhra Pradesh. So before 2014, we don't have any data on Telangana.**"""

#Changing some states name to repeat duplicates and aviod error in geomapping
crimes_df['STATE/UT'].replace("A & N ISLANDS", "ANDAMAN AND NICOBAR", inplace = True)
crimes_df['STATE/UT'].replace("A&N ISLANDS", "ANDAMAN AND NICOBAR", inplace = True)
crimes_df['STATE/UT'].replace("D&N HAVELI", "DADRA AND NAGAR HAVELI", inplace = True)
crimes_df['STATE/UT'].replace("D & N HAVELI", "DADRA AND NAGAR HAVELI", inplace = True)
crimes_df['STATE/UT'].replace("DELHI UT", "DELHI", inplace = True)
crimes_df['STATE/UT'].replace("TELANGANA", "ANDHRA PRADESH", inplace = True)
crimes_df['STATE/UT'].replace("JAMMU & KASHMIR", "JAMMU AND KASHMIR", inplace = True)
crimes_df['STATE/UT'].replace("DAMAN & DIU", "DAMAN AND DIU", inplace = True)

#After removing entries

crimes_df['STATE/UT'].unique()
len(crimes_df['STATE/UT'].unique())

crimes_df['STATE/UT'].unique()

crimes_df.isnull().sum()

"""We checked for the null values in our dataset and found nothing. So we do not have anything else to clean in our data. We can start the fun part now i.e Analysing and plotting graphs."""

crimes_df

def crimes_by_different_order(dataframe,column_name):
    "This function returns a dataframe with total number of particular crimes grouping by certain column"
    for column in list(crimes_df.columns)[3:]:
        dataframe[column]=crimes_df.groupby([column_name])[column].sum()
    return dataframe

#creating a new empty dataframe
total_crimes_in_years_df=pd.DataFrame()
total_crimes_in_years_df=crimes_by_different_order(total_crimes_in_years_df,"Year")
total_crimes_in_years_df.reset_index(inplace=True)
total_crimes_in_years_df

total_crimes_in_years_df['Total Number of Cases']=total_crimes_in_years_df.sum(axis=1)
total_crimes_in_years_df["Total Number of Cases"].sum()

"""More than 26 lakh cases were registered between 2001 to 2014."""

def plot_figure(title, crime,ylabel,color="red"):
    "This function generate a bar graph using the total_crimes_in_years_df"
    fig = go.Figure(data=[go.Bar(
            x=total_crimes_in_years_df["Year"], y=total_crimes_in_years_df[crime],
            text=total_crimes_in_years_df[crime],
        )])
    fig.update_traces(texttemplate='%{text:.2s}', textposition='outside',marker_color=color)
    fig.update_layout(title=title,
                       xaxis = dict(title='Years',
                                    tickmode = 'linear',
                                    tickangle=-30 ),
                   yaxis_title=ylabel,uniformtext_minsize=8, uniformtext_mode='show')

    fig.show()

plot_figure("Rape cases in India in 2001-2014","Rape","Cases of Rape in India", color='lightslategray')

"""Increase of more than 56% in rape cases in 2014 than in 2001."""

plot_figure("Kidnapping and Abduction cases in India in 2001-2014","Kidnapping and Abduction","Cases of Kidnapping and Abduction in India", color='crimson')

"""Triples the cases of Kidnapping and abduction were registered in 2014 than in 2001."""

plot_figure("Dowry death cases in India in 2001-2014","Dowry Deaths","Cases of Dowry deaths in India", color="navy")

"""Through the literacy rate of India is increased by more than 75%, there is not much change in dowry cases."""

plot_figure("Assault to her modesty in 2001-2014","Assault on women with intent to outrage her modesty","Cases of Assaulting a women for her modesty in India", color='rgb(158,202,225)')

"""Assualt to modesty had a spike of more than 60%."""

plot_figure("Domestic Violence cases in India in 2001-2014","Cruelty by Husband or his Relatives","Cases of Domestic Violence in India", color='lightsalmon')

"""Even in the 21st century, society doesn't know to treat and respect women at home. The Domestic Violence cases were 60% more in 2014 than in 2001."""

plot_figure("Importation of girls in India in 2001-2014","Importation of Girls","Cases ofImportation of girls in India", color="indianred")

"""Importation of girl is the only crime which had reduced considerably. There was a reduction of 88% from 2001 to 2014."""

#Year wise line graph
fig = go.Figure(data=[go.Scatter(
            x=total_crimes_in_years_df["Year"], y=total_crimes_in_years_df["Total Number of Cases"],
            text=total_crimes_in_years_df["Total Number of Cases"],
        )])
fig.update_layout(title="Year wise crime against women in India(including States & UT)",
                       xaxis = dict(title='Years',
                                    tickmode = 'linear',
                                    tickangle=-30 ),
                      #yaxis=dict(title=, tickmode = 'linear', tick0 = 0.0,dtick = 0.25)
                   yaxis_title="Cases",yaxis_tickformat = 's',uniformtext_minsize=8, uniformtext_mode='show')

fig.show()

"""There is a steady change in crime during 2012-13. This also shows that number of crimes against women is increasing at a huge rate."""

#Rate of change of different crimes over time

fig = go.Figure()
color=["firebrick","royalblue","rgb(0, 204, 150)"]
dash=["solid","dash","dot"]
j=0
for i in total_crimes_in_years_df.columns:
    if i=="Total Number of Cases":
        break
    if i == "Year":
        continue
    fig.add_trace(go.Scatter(x=total_crimes_in_years_df.Year, y=total_crimes_in_years_df[i], name=i,
                         line=dict(color=color[j % len(color)], width=4, dash=dash[j % len(dash)])))
    j=j+1
# Edit the layout
fig.update_layout(title='Rate of change of different crime over time',
                   xaxis_title='Years',
                   yaxis_title='Spread of Cases')

fig.show()
fig = go.Figure()

crimes_in_years_df=total_crimes_in_years_df.drop("Total Number of Cases", axis=1)
crimes_in_years_df.set_index("Year", inplace = True)

"""# Which was highest reported crime and which one was least ?"""

pd.DataFrame(crimes_in_years_df.sum(axis=0),columns=['Count']).sort_values(by='Count',ascending=False)

"""Domestic Violence is the highest reported crime and Importation of girls is least reported.

# Percentange of each crime in between 2001-2014 piechart
"""

fig = px.pie(pd.DataFrame(crimes_in_years_df.sum(axis=0),columns=['Count']), values='Count', names=pd.DataFrame(crimes_in_years_df.sum(axis=0)).index, title='Percentage of Each Crime between 2001 - 2014')
fig.show()

"""## State/UT wise Analysis

Note: I have merged Telangana and Andhra Pradesh.
"""

state_ut_crimes_df=pd.DataFrame()
state_ut_crimes_df=crimes_by_different_order(state_ut_crimes_df,"STATE/UT")
state_ut_crimes_df

state_ut_crimes_df.shape

"""### Top 10 States/Union Territories With Highest number of crime cases"""

pd.DataFrame(state_ut_crimes_df.sum(axis=1),columns=['Total Cases'] ).sort_values(by='Total Cases',ascending=False).head(10).style.background_gradient(cmap = "Reds")

"""Andhra Pradesh has the highest number of crime cases. Uttar Pradesh is the second highest.
**Note:** Without the merging of Andhra Pradesh and Telangana, Uttar Pradesh will be the state with the highest number of cases.

### Top 10 States/Union Territories With Lowest Crime Rate
"""

pd.DataFrame(state_ut_crimes_df.sum(axis=1),columns=['Total Cases'] ).sort_values(by='Total Cases').head(10).style.background_gradient(cmap = "YlGn")

"""Lakshadweep has the lowest crime rate.

### Out of 7 types of crime which are the states/ut having maximum cases of each type ?
"""

pd.DataFrame(state_ut_crimes_df.idxmax(),columns=['STATE / UT'])

"""Can be officially declared Madhya Pradesh has the worst state?🙄

### Out of 7 types of crime which are the states/ut having minimum cases of each type ?
"""

pd.DataFrame(state_ut_crimes_df.idxmin(),columns=['STATE / UT'])

"""Lakshadweep is the most secure UT for women.

# Function For Specific State/UT Analysis
### Enter name of the State/UT for which you want to analyze crime rate over 14 Years
"""

def which_state_you_want_to_analyze(state_name):
    try:
        fig = px.pie(state_ut_crimes_df, values=state_ut_crimes_df.loc[state_name],
                     names=state_ut_crimes_df.iloc[0,:].index, title='Total Crime Rate Distribution for {}'.format(state_name))
        fig.show()
    except KeyError:
        print('You Entered Wrong STATE/UT Name')

state_name=input('Enter Name of State/UT : ').upper()
which_state_you_want_to_analyze(state_name)

"""# Plotting Crime on the map of India

GeoJSON file may have the name of the states and UT in a different case than in the Dataframe.
In our case, the data frame contains the state/ut name in UPPER case and  GeoJSON has names in title case.

Thus, we will be modifying the file and will dump all the data in the new GeoJSON file named **result.json**.
"""

#Modfying the json files.
#Changing the statename to uppercases. So it matches with the states names in our dataset
with open('/content/india_states.geojson', 'r') as fp:
    js=json.load(fp)

for i in range(len(js["features"])):
    ls=[js["features"][i]["properties"]["NAME_1"]]
    js["features"][i]["properties"]["NAME_1"]=ls[0].upper()

#dumping the names in the new json files named result.json and opening it
with open('/content/result.json', 'w') as fil:
    json.dump(js, fil)

with open('/content/result.json', 'r') as fp:
    india_geojson = json.load(fp)

"""Creating an ID column in our data frame which matches with the ID key in our GeoJSON files. Every State and UT has a unique ID number in our GeoJSON file. We will be copying those ID number from the file to the dataframe for that particular state."""

state_ut_crimes_df.reset_index(inplace=True)

#Adding a id column in the state dataframe which as the same value for a particular as the GeoJSON as for that state.
state_id_map = {}
for feature in india_geojson["features"]:
    feature["id"] = feature["properties"]["ID_1"]
    state_id_map[feature["properties"]["NAME_1"]] = feature["id"]

state_ut_crimes_df["id"] = state_ut_crimes_df['STATE/UT'].apply(lambda x: state_id_map[x])

state_ut_crimes_df

"""We have added id columns in our dataframe. Now defining a dictionary which will help users to easily map column name of dataframe to the crime they want in the map using the numbers as the key."""

crime_dict={1:'Rape', 2: 'Kidnapping and Abduction',3: 'Dowry Deaths',
       4: 'Assault on women with intent to outrage her modesty',
       5: 'Insult to modesty of Women', 6: 'Cruelty by Husband or his Relatives',
       7: 'Importation of Girls'}

def plotmap(crime_name):
    "This function plot different crimes on india map using the stat_ut_crimes_df and GeoJson data"
    fig = px.choropleth(state_ut_crimes_df, geojson=india_geojson, locations='id', color= crime_name,
                           hover_name="STATE/UT", color_continuous_scale="Viridis",
                           hover_data=[crime_name],
                           title=' '.join([str(crime_name), 'cases in India(2001-2014)'])
                          )
    fig.update_geos(fitbounds="locations", visible=False)
    # Use fig.show() if you want to plot the map in the jupyter notebook itself. This will increase the size of notebook.
    #To control the size of notebook I used the fig.write_html() which will create a new html file and open it in new tab
    #fig.show()
    fig.write_html("output.html",include_plotlyjs="cdn",auto_open=True)

for key, value in crime_dict.items():
    print ("{:<10} {:<10}".format(key, value))

i=True
while i==True:
    try:
        crime_name=int(input("Enter the number from previous cell which is representing the crime you want to plot on map: "))
    except ValueError:
        print('\nYou did not enter a valid integer')
        break
    plotmap(crime_dict[crime_name])
    print("Want to draw another map? Press 'Y' for yes or press any another key for no.")
    another_map=input().upper()
    if another_map!='Y':
        i=False
        break
    IPython.display.clear_output()

"""## Inferences and Conclusion

India is one of the worst country for women in the world. And in recent time it is getting badder when crimes against women are happening in the name of their religion.
According to [scroll.in](https://scroll.in/article/753496/crimes-against-women-reported-every-two-minutes-in-india), 26 crimes against women are reported every hour, or one complaint every two minutes.

**Andhra Pradesh had registered the most crimes against women** from 2001 to 2014. Uttar Pradesh and West Bengal were second and third states with the most number of crimes against women.
Andhra Pradesh also reported the highest number of cases of Insult to the modesty of Women.

**Madhya Pradesh reported the most number of Rape cases and Assualt to her modest cases.** Madhya Pradesh was also the fifth highest state with the most number of registered crime cases against women.

**Uttar Pradesh reported the most number of Kidnapping and Abduction and Dowry Deaths.** Seriously, still dowry!!!. The world is in the 21st century but UP is still in the 18th century.

Madhya Pradesh, Andhra Pradesh, Uttar Pradesh, Rajasthan and West Bengal account for almost half of all crimes committed against women around the country from 2001 to 2014.

If you have any suggestions or want anymore type of analysis from this dataset, please let me know. Thank you.
"""

jovian.commit(project=project_name)